{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "7.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-7.0.6.jar",
          "url": "spring-webmvc-7.0.6.jar",
          "size": 1105558,
          "sha512": "3f75c617fb3308ce0ff59e75f06d5ae57137dd7db8cb2904854a3179f7e629e590105ef3841e08f160004aee02f341d5949225bca79bfd5f6331e1a2b16db395",
          "sha256": "fc8decebcd5d02f33ddb6f900e7b34241c6a0faa82c945859c5a8d56ca2e0e30",
          "sha1": "da516a887d0fea326c16b07fb2519f7f112f8eda",
          "md5": "c9fd829100752692c38ff92a9619d26b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-7.0.6.jar",
          "url": "spring-webmvc-7.0.6.jar",
          "size": 1105558,
          "sha512": "3f75c617fb3308ce0ff59e75f06d5ae57137dd7db8cb2904854a3179f7e629e590105ef3841e08f160004aee02f341d5949225bca79bfd5f6331e1a2b16db395",
          "sha256": "fc8decebcd5d02f33ddb6f900e7b34241c6a0faa82c945859c5a8d56ca2e0e30",
          "sha1": "da516a887d0fea326c16b07fb2519f7f112f8eda",
          "md5": "c9fd829100752692c38ff92a9619d26b"
        }
      ]
    }
  ]
}
