{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-micrometer-metrics",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-observation",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-micrometer-metrics-4.0.5.jar",
          "url": "spring-boot-micrometer-metrics-4.0.5.jar",
          "size": 240648,
          "sha512": "fd5d96b1f01d82f11e6028101ef672c2ccc62ad756c3d1f7a890783ad1140a5ef8dace567f4ab3b7564509a7803f57dee94007b694e52e004d0eb049df649324",
          "sha256": "4cb7a8ca21b17a31b5d6b6ca1e557c466b0f9ced80bd5f0359b5aad390db0004",
          "sha1": "79dc558c123997a8af99fc33b8a7d6bb1978eb8f",
          "md5": "00184c8d8f4bb8744319416023edc3da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-observation",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-micrometer-metrics-4.0.5.jar",
          "url": "spring-boot-micrometer-metrics-4.0.5.jar",
          "size": 240648,
          "sha512": "fd5d96b1f01d82f11e6028101ef672c2ccc62ad756c3d1f7a890783ad1140a5ef8dace567f4ab3b7564509a7803f57dee94007b694e52e004d0eb049df649324",
          "sha256": "4cb7a8ca21b17a31b5d6b6ca1e557c466b0f9ced80bd5f0359b5aad390db0004",
          "sha1": "79dc558c123997a8af99fc33b8a7d6bb1978eb8f",
          "md5": "00184c8d8f4bb8744319416023edc3da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-micrometer-metrics-4.0.5-javadoc.jar",
          "url": "spring-boot-micrometer-metrics-4.0.5-javadoc.jar",
          "size": 528629,
          "sha512": "60561a4cc8e40028fe6b44ad55b32a3f5231125f00527c65b20941c5bb8ac6df5e7795fe54ac103b4db6d58b9f505ca04b3526d73d8fe2fb0e3b8f1812645079",
          "sha256": "ec9112e32041fa3f802f08b14ced220705a4826566dccc770f8752be8aa1563a",
          "sha1": "f6fefe220197da2b9610642082bd1b7f24f8df60",
          "md5": "0b576448bc7913f78f7860e117696e11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-micrometer-metrics-4.0.5-sources.jar",
          "url": "spring-boot-micrometer-metrics-4.0.5-sources.jar",
          "size": 169009,
          "sha512": "9ed577111e1bb35463d8a78d31f5ad143ffa9b009760b4cf8f025df605a02df46638f6b0df5ee21c3ba40718eeadb14d5a4dac41c59cedbcf467e09b2cee0816",
          "sha256": "61b4faa51380896f2106ab56c2e55dff80b8bef7b445a8cde2cde2713bfd6771",
          "sha1": "4e421ac62b59b379a30ee6942abc2eb1236282f0",
          "md5": "12de03d85a7467ce2343274fdaca4084"
        }
      ]
    }
  ]
}
