{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-micrometer-observation",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-micrometer-observation-4.0.5.jar",
          "url": "spring-boot-micrometer-observation-4.0.5.jar",
          "size": 28846,
          "sha512": "92cb61cfc4bc7cbf55a484a5e89fa47bbb2730451bec9c7eabd6e26588e11e2ce8dbce3b1d44d427f36cba81653c76c3b0bb96e835797c2148ac76d662795b28",
          "sha256": "59e9f36ee2f3492afe0ed21a0f81f5f2e0131b89aaf001ea0244ad3e9c939b3e",
          "sha1": "490c94bfb870ab271eb1fd9390aaf03eda4575dc",
          "md5": "0c14bf2435be5289eb2138f60afa9fb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-micrometer-observation-4.0.5.jar",
          "url": "spring-boot-micrometer-observation-4.0.5.jar",
          "size": 28846,
          "sha512": "92cb61cfc4bc7cbf55a484a5e89fa47bbb2730451bec9c7eabd6e26588e11e2ce8dbce3b1d44d427f36cba81653c76c3b0bb96e835797c2148ac76d662795b28",
          "sha256": "59e9f36ee2f3492afe0ed21a0f81f5f2e0131b89aaf001ea0244ad3e9c939b3e",
          "sha1": "490c94bfb870ab271eb1fd9390aaf03eda4575dc",
          "md5": "0c14bf2435be5289eb2138f60afa9fb7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-micrometer-observation-4.0.5-javadoc.jar",
          "url": "spring-boot-micrometer-observation-4.0.5-javadoc.jar",
          "size": 135672,
          "sha512": "785a927e46c665c687d1a8bb27c60a421c186f150e284c9083d53aa982be6d5eb2ce7f9ab15fc7b7d5ffe60b884ba7bb34c033cdcc18a6b94631de9889774477",
          "sha256": "b6456297c58d33a8836f50a320b41af41e9c0b147dc5e6cf263e93dc612df136",
          "sha1": "61a08a78e5f0f19ab18f3382b5844b5f504b04aa",
          "md5": "b61bac11cf9b504e1cc411a714849e54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-micrometer-observation-4.0.5-sources.jar",
          "url": "spring-boot-micrometer-observation-4.0.5-sources.jar",
          "size": 19810,
          "sha512": "2dd313f77860f9eaf21f1cdd2fbbd81ea1e367f3c636f0f849ae9a363bdca27f6d28c087943e878693160101b8e71c427ff037148620188aef01ae7bb0200364",
          "sha256": "0cdce3419f7e7fbdaa9134438392fa975783a903cdfb68f1928c4ccbe30c84c5",
          "sha1": "38b9aea763a075a60c7b81c08bd2070d4943b6f6",
          "md5": "9e538df710d15f95f04e255b6ef97a31"
        }
      ]
    }
  ]
}
