{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-websocket",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webmvc",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-websocket",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-websocket-4.0.5.jar",
          "url": "spring-boot-starter-websocket-4.0.5.jar",
          "size": 4755,
          "sha512": "afc517cbda5371a7804f8a211de24f7b39f8ecfb9d1a5796f790410f5da3ab8c9aff76a36ab12e00f06b30508c4976b3087db46cdfa7952fe695f565966ffdab",
          "sha256": "7b0cc93e64ffd6ed2369102c791556751a0fe771c9c37c6450656ba80038d92f",
          "sha1": "48fbd356754c737bb1cca62e91e11d33490a2035",
          "md5": "9dcd540fa652ef199b19625df6e0f826"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webmvc",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-websocket",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-websocket-4.0.5.jar",
          "url": "spring-boot-starter-websocket-4.0.5.jar",
          "size": 4755,
          "sha512": "afc517cbda5371a7804f8a211de24f7b39f8ecfb9d1a5796f790410f5da3ab8c9aff76a36ab12e00f06b30508c4976b3087db46cdfa7952fe695f565966ffdab",
          "sha256": "7b0cc93e64ffd6ed2369102c791556751a0fe771c9c37c6450656ba80038d92f",
          "sha1": "48fbd356754c737bb1cca62e91e11d33490a2035",
          "md5": "9dcd540fa652ef199b19625df6e0f826"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-websocket-4.0.5-javadoc.jar",
          "url": "spring-boot-starter-websocket-4.0.5-javadoc.jar",
          "size": 4755,
          "sha512": "afc517cbda5371a7804f8a211de24f7b39f8ecfb9d1a5796f790410f5da3ab8c9aff76a36ab12e00f06b30508c4976b3087db46cdfa7952fe695f565966ffdab",
          "sha256": "7b0cc93e64ffd6ed2369102c791556751a0fe771c9c37c6450656ba80038d92f",
          "sha1": "48fbd356754c737bb1cca62e91e11d33490a2035",
          "md5": "9dcd540fa652ef199b19625df6e0f826"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-websocket-4.0.5-sources.jar",
          "url": "spring-boot-starter-websocket-4.0.5-sources.jar",
          "size": 4755,
          "sha512": "afc517cbda5371a7804f8a211de24f7b39f8ecfb9d1a5796f790410f5da3ab8c9aff76a36ab12e00f06b30508c4976b3087db46cdfa7952fe695f565966ffdab",
          "sha256": "7b0cc93e64ffd6ed2369102c791556751a0fe771c9c37c6450656ba80038d92f",
          "sha1": "48fbd356754c737bb1cca62e91e11d33490a2035",
          "md5": "9dcd540fa652ef199b19625df6e0f826"
        }
      ]
    }
  ]
}
