{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-micrometer-metrics",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-metrics",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-4.0.5.jar",
          "url": "spring-boot-starter-micrometer-metrics-4.0.5.jar",
          "size": 4748,
          "sha512": "f2bbae26ebdd4cea28268e4eaf42d76779e126cf179486b764dd1c5548d51904602ae947263ccf4d2287875c8c157b63c3739feda2ba8c7a1d71ec7dd9b35efa",
          "sha256": "78a37aa878c3b899929fd17d31f3d5c9b96d882a7d9acbb0b7f62d154d0f4bac",
          "sha1": "6d1a06aa3dbb5616204efcc172ddc4565b84692a",
          "md5": "d15b93f8f3be69eb8153109772086f68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-micrometer-metrics",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-4.0.5.jar",
          "url": "spring-boot-starter-micrometer-metrics-4.0.5.jar",
          "size": 4748,
          "sha512": "f2bbae26ebdd4cea28268e4eaf42d76779e126cf179486b764dd1c5548d51904602ae947263ccf4d2287875c8c157b63c3739feda2ba8c7a1d71ec7dd9b35efa",
          "sha256": "78a37aa878c3b899929fd17d31f3d5c9b96d882a7d9acbb0b7f62d154d0f4bac",
          "sha1": "6d1a06aa3dbb5616204efcc172ddc4565b84692a",
          "md5": "d15b93f8f3be69eb8153109772086f68"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-4.0.5-javadoc.jar",
          "url": "spring-boot-starter-micrometer-metrics-4.0.5-javadoc.jar",
          "size": 4748,
          "sha512": "f2bbae26ebdd4cea28268e4eaf42d76779e126cf179486b764dd1c5548d51904602ae947263ccf4d2287875c8c157b63c3739feda2ba8c7a1d71ec7dd9b35efa",
          "sha256": "78a37aa878c3b899929fd17d31f3d5c9b96d882a7d9acbb0b7f62d154d0f4bac",
          "sha1": "6d1a06aa3dbb5616204efcc172ddc4565b84692a",
          "md5": "d15b93f8f3be69eb8153109772086f68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-micrometer-metrics-4.0.5-sources.jar",
          "url": "spring-boot-starter-micrometer-metrics-4.0.5-sources.jar",
          "size": 4748,
          "sha512": "f2bbae26ebdd4cea28268e4eaf42d76779e126cf179486b764dd1c5548d51904602ae947263ccf4d2287875c8c157b63c3739feda2ba8c7a1d71ec7dd9b35efa",
          "sha256": "78a37aa878c3b899929fd17d31f3d5c9b96d882a7d9acbb0b7f62d154d0f4bac",
          "sha1": "6d1a06aa3dbb5616204efcc172ddc4565b84692a",
          "md5": "d15b93f8f3be69eb8153109772086f68"
        }
      ]
    }
  ]
}
