{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webmvc",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webmvc",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.0.5.jar",
          "url": "spring-boot-starter-webmvc-4.0.5.jar",
          "size": 4749,
          "sha512": "3ad51e94d54c8ec328b46adfd086648c568fd47d8e32970b12a016cc0ed06f2a7ea4794e0c48fa7ca8f43556b13b87d87f9945995d333d69c9261d28cfa6ae82",
          "sha256": "a59ed2815e5531957726620a5f6c80d2e46f8c3ef2b8b35c849c661e73b7ca06",
          "sha1": "3bb411e29fbfb48fa378eb7ca6d11dedc6a8b3e8",
          "md5": "cad2dcbd44d45a4831b337d1427c853a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webmvc",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.0.5.jar",
          "url": "spring-boot-starter-webmvc-4.0.5.jar",
          "size": 4749,
          "sha512": "3ad51e94d54c8ec328b46adfd086648c568fd47d8e32970b12a016cc0ed06f2a7ea4794e0c48fa7ca8f43556b13b87d87f9945995d333d69c9261d28cfa6ae82",
          "sha256": "a59ed2815e5531957726620a5f6c80d2e46f8c3ef2b8b35c849c661e73b7ca06",
          "sha1": "3bb411e29fbfb48fa378eb7ca6d11dedc6a8b3e8",
          "md5": "cad2dcbd44d45a4831b337d1427c853a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.0.5-javadoc.jar",
          "url": "spring-boot-starter-webmvc-4.0.5-javadoc.jar",
          "size": 4749,
          "sha512": "3ad51e94d54c8ec328b46adfd086648c568fd47d8e32970b12a016cc0ed06f2a7ea4794e0c48fa7ca8f43556b13b87d87f9945995d333d69c9261d28cfa6ae82",
          "sha256": "a59ed2815e5531957726620a5f6c80d2e46f8c3ef2b8b35c849c661e73b7ca06",
          "sha1": "3bb411e29fbfb48fa378eb7ca6d11dedc6a8b3e8",
          "md5": "cad2dcbd44d45a4831b337d1427c853a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.0.5-sources.jar",
          "url": "spring-boot-starter-webmvc-4.0.5-sources.jar",
          "size": 4749,
          "sha512": "3ad51e94d54c8ec328b46adfd086648c568fd47d8e32970b12a016cc0ed06f2a7ea4794e0c48fa7ca8f43556b13b87d87f9945995d333d69c9261d28cfa6ae82",
          "sha256": "a59ed2815e5531957726620a5f6c80d2e46f8c3ef2b8b35c849c661e73b7ca06",
          "sha1": "3bb411e29fbfb48fa378eb7ca6d11dedc6a8b3e8",
          "md5": "cad2dcbd44d45a4831b337d1427c853a"
        }
      ]
    }
  ]
}
