{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-actuator",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-4.0.5.jar",
          "url": "spring-boot-actuator-4.0.5.jar",
          "size": 356813,
          "sha512": "e1bafdb9412b584fcf2075d12fbcf7d61d7bfae4bc4ed69c586482f4cc72fefb040774e94a084bec4afe79e40f0fdfd3d3502e879d135be63b32ada0890cbb0a",
          "sha256": "5b36c36561c0c62f23be82438835e32dbc576b871d956333ca5b258a9513fcb8",
          "sha1": "023035a9e13f827bba5b81bf7f336ee14d1a13a8",
          "md5": "2c889d1979e86d4e95ce7ef26f15fba4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-4.0.5.jar",
          "url": "spring-boot-actuator-4.0.5.jar",
          "size": 356813,
          "sha512": "e1bafdb9412b584fcf2075d12fbcf7d61d7bfae4bc4ed69c586482f4cc72fefb040774e94a084bec4afe79e40f0fdfd3d3502e879d135be63b32ada0890cbb0a",
          "sha256": "5b36c36561c0c62f23be82438835e32dbc576b871d956333ca5b258a9513fcb8",
          "sha1": "023035a9e13f827bba5b81bf7f336ee14d1a13a8",
          "md5": "2c889d1979e86d4e95ce7ef26f15fba4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-4.0.5-javadoc.jar",
          "url": "spring-boot-actuator-4.0.5-javadoc.jar",
          "size": 850299,
          "sha512": "85335004d3ff1733d4478534193701009648a5478f5e3fb43541ab79b87dabe8c9ece7d3e4892e51a96956e3caaf0e0584dc70faffbb2b3499f04c7bcdc1d4fc",
          "sha256": "5ba8dff44519f2372c67551a0daf6cff09c362ae756555d40d11aec185bab01a",
          "sha1": "9a8acf3b6c042a16ff3357dcef76a12ba4df1ed8",
          "md5": "fd5fad0752d692998952878067367bf3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-4.0.5-sources.jar",
          "url": "spring-boot-actuator-4.0.5-sources.jar",
          "size": 242903,
          "sha512": "5c08cb21079f16ff7d04c90710717edb8f23f570bb83587626ff6a2def107f717b37add440bab8548d2610f65708821763330e6f57f0bd7e6ad9deb16cb4dccc",
          "sha256": "e4dae9c19b9a68785da131808ce89df71d657bec55da7f6458aaa70f2b897bfc",
          "sha1": "3d5c131e229e6dec70f57f6d409e0fa07280d72e",
          "md5": "ea4659e28eaf01c9e923c695f5bc1ea5"
        }
      ]
    }
  ]
}
