CREATE TABLE IF NOT EXISTS canvas_seasons (
  id UUID PRIMARY KEY,
  season_code VARCHAR(16) NOT NULL UNIQUE,
  title VARCHAR(64) NOT NULL,
  width SMALLINT NOT NULL,
  height SMALLINT NOT NULL,
  status VARCHAR(16) NOT NULL,
  starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
  ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  archived_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_canvas_seasons_status_starts
  ON canvas_seasons(status, starts_at DESC);

CREATE TABLE IF NOT EXISTS canvas_pixels (
  season_id UUID NOT NULL,
  x SMALLINT NOT NULL,
  y SMALLINT NOT NULL,
  color_int INTEGER NOT NULL,
  nickname VARCHAR(32),
  placed_at TIMESTAMP WITH TIME ZONE,
  placed_by_ip_hash VARCHAR(128),
  version INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (season_id, x, y),
  CONSTRAINT fk_canvas_pixels_season FOREIGN KEY (season_id) REFERENCES canvas_seasons(id) ON DELETE CASCADE,
  CONSTRAINT chk_canvas_pixels_x CHECK (x BETWEEN 0 AND 511),
  CONSTRAINT chk_canvas_pixels_y CHECK (y BETWEEN 0 AND 511),
  CONSTRAINT chk_canvas_pixels_color CHECK (color_int BETWEEN 0 AND 16777215)
);

CREATE TABLE IF NOT EXISTS canvas_pixel_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id UUID NOT NULL,
  x SMALLINT NOT NULL,
  y SMALLINT NOT NULL,
  prev_color_int INTEGER NOT NULL,
  new_color_int INTEGER NOT NULL,
  nickname VARCHAR(32),
  ip_hash VARCHAR(128) NOT NULL,
  placed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  request_id UUID NOT NULL UNIQUE,
  CONSTRAINT fk_canvas_pixel_events_season FOREIGN KEY (season_id) REFERENCES canvas_seasons(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_canvas_pixel_events_season_placed
  ON canvas_pixel_events(season_id, placed_at DESC);

CREATE INDEX IF NOT EXISTS idx_canvas_pixel_events_coord
  ON canvas_pixel_events(season_id, x, y, placed_at DESC);

CREATE TABLE IF NOT EXISTS canvas_cooldowns (
  ip_hash VARCHAR(128) PRIMARY KEY,
  next_place_at TIMESTAMP WITH TIME ZONE NOT NULL,
  last_place_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS canvas_history_assets (
  season_id UUID PRIMARY KEY,
  thumbnail_pixels TEXT NOT NULL,
  pixel_count INTEGER NOT NULL,
  participant_count INTEGER NOT NULL,
  dominant_colors TEXT,
  generated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_canvas_history_assets_season FOREIGN KEY (season_id) REFERENCES canvas_seasons(id) ON DELETE CASCADE
);
