{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-actuator",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-micrometer-metrics",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-health",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-4.0.5.jar",
          "url": "spring-boot-starter-actuator-4.0.5.jar",
          "size": 4805,
          "sha512": "38fb3b2fa3fb14d03f61d0fb78174dcec5385f60d6a7c7c7bfbb950598309ae783fedccdae2feff3af65a2bc50186da1fe169a8b795d75294524dc99b96837d1",
          "sha256": "fb4ad6c42bf8c60ad238a0d64a63070307d5c0c5915706ab69ecab6b3577cf6e",
          "sha1": "6600aacfa36a412ac113b450dfc4c3a0d8e70611",
          "md5": "f288ab9c9dc02a4445da15e1f6a60c11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-micrometer-metrics",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-health",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-4.0.5.jar",
          "url": "spring-boot-starter-actuator-4.0.5.jar",
          "size": 4805,
          "sha512": "38fb3b2fa3fb14d03f61d0fb78174dcec5385f60d6a7c7c7bfbb950598309ae783fedccdae2feff3af65a2bc50186da1fe169a8b795d75294524dc99b96837d1",
          "sha256": "fb4ad6c42bf8c60ad238a0d64a63070307d5c0c5915706ab69ecab6b3577cf6e",
          "sha1": "6600aacfa36a412ac113b450dfc4c3a0d8e70611",
          "md5": "f288ab9c9dc02a4445da15e1f6a60c11"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-4.0.5-javadoc.jar",
          "url": "spring-boot-starter-actuator-4.0.5-javadoc.jar",
          "size": 4805,
          "sha512": "38fb3b2fa3fb14d03f61d0fb78174dcec5385f60d6a7c7c7bfbb950598309ae783fedccdae2feff3af65a2bc50186da1fe169a8b795d75294524dc99b96837d1",
          "sha256": "fb4ad6c42bf8c60ad238a0d64a63070307d5c0c5915706ab69ecab6b3577cf6e",
          "sha1": "6600aacfa36a412ac113b450dfc4c3a0d8e70611",
          "md5": "f288ab9c9dc02a4445da15e1f6a60c11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-4.0.5-sources.jar",
          "url": "spring-boot-starter-actuator-4.0.5-sources.jar",
          "size": 4805,
          "sha512": "38fb3b2fa3fb14d03f61d0fb78174dcec5385f60d6a7c7c7bfbb950598309ae783fedccdae2feff3af65a2bc50186da1fe169a8b795d75294524dc99b96837d1",
          "sha256": "fb4ad6c42bf8c60ad238a0d64a63070307d5c0c5915706ab69ecab6b3577cf6e",
          "sha1": "6600aacfa36a412ac113b450dfc4c3a0d8e70611",
          "md5": "f288ab9c9dc02a4445da15e1f6a60c11"
        }
      ]
    }
  ]
}
