{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat-runtime",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.20"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.20"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.20"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.5.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.5.jar",
          "size": 4745,
          "sha512": "839c6b5abc9f549e6d6149da711ef75f2204521989f7a7341d4170dd37804601305745487e0b7dc8974fa22882abdf7cc2bcf28b8c5b742aa75b9b073e8901b9",
          "sha256": "1df5c0fcbfdfeeacee61424810312169eed36f8525f1cd91711b584760ed518f",
          "sha1": "d352a6c24ad93d1518233ddce144a180d491073b",
          "md5": "7ec818745695a329bc21e26aaa632891"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.20"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.20"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.20"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.5.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.5.jar",
          "size": 4745,
          "sha512": "839c6b5abc9f549e6d6149da711ef75f2204521989f7a7341d4170dd37804601305745487e0b7dc8974fa22882abdf7cc2bcf28b8c5b742aa75b9b073e8901b9",
          "sha256": "1df5c0fcbfdfeeacee61424810312169eed36f8525f1cd91711b584760ed518f",
          "sha1": "d352a6c24ad93d1518233ddce144a180d491073b",
          "md5": "7ec818745695a329bc21e26aaa632891"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.5-javadoc.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.5-javadoc.jar",
          "size": 4745,
          "sha512": "839c6b5abc9f549e6d6149da711ef75f2204521989f7a7341d4170dd37804601305745487e0b7dc8974fa22882abdf7cc2bcf28b8c5b742aa75b9b073e8901b9",
          "sha256": "1df5c0fcbfdfeeacee61424810312169eed36f8525f1cd91711b584760ed518f",
          "sha1": "d352a6c24ad93d1518233ddce144a180d491073b",
          "md5": "7ec818745695a329bc21e26aaa632891"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.5-sources.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.5-sources.jar",
          "size": 4745,
          "sha512": "839c6b5abc9f549e6d6149da711ef75f2204521989f7a7341d4170dd37804601305745487e0b7dc8974fa22882abdf7cc2bcf28b8c5b742aa75b9b073e8901b9",
          "sha256": "1df5c0fcbfdfeeacee61424810312169eed36f8525f1cd91711b584760ed518f",
          "sha1": "d352a6c24ad93d1518233ddce144a180d491073b",
          "md5": "7ec818745695a329bc21e26aaa632891"
        }
      ]
    }
  ]
}
